# Generated by Django 4.0.1 on 2024-04-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=900)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('idproof', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('propname', models.CharField(max_length=100)),
                ('propphoto', models.CharField(max_length=500)),
                ('propemail', models.CharField(max_length=100)),
                ('propphone', models.BigIntegerField()),
                ('website', models.CharField(max_length=100)),
                ('openingtime', models.CharField(max_length=100)),
                ('closingtime', models.CharField(max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('fromtime', models.CharField(default='', max_length=100)),
                ('totime', models.CharField(default='', max_length=100)),
                ('expectedtime', models.CharField(default='', max_length=100)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=900)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=400)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from1', to='myapp.login')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to1', to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=900)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rating', models.CharField(max_length=100)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bussiness')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=900)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meassage', models.CharField(max_length=900)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness1', to='myapp.login')),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer1', to='myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='bussiness',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('SLOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slot')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
