# Generated by Django 4.0.1 on 2024-04-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='BUSSINESS',
            new_name='FROM',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='CUSTOMER',
            new_name='TO',
        ),
    ]
